=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/020_notes/notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="notes"> <!-- Définit un élément nommé DemoEtu-A25, qui est la racine du document XML -->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="note" maxOccurs="unbounded"> <!-- maxOccurs="unbounded" : Il peut y avoir un nombre illimité de note -->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="to" type="xs:string"/>
                            <xs:element name="from" type="xs:string"/>
                            <xs:element name="heading" type="xs:string"/>
                            <xs:element name="body" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/020_notes/notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="notes.xsd">
    <note>
        <to>Partick</to>
        <from>Lucie</from>
        <heading>Rappel</heading>
        <body>N'oublie pas la réunion demain.</body>
    </note>
    <note>
        <to>Vincent</to>
        <from>Sophie</from>
        <heading>Invitation</heading>
        <body>Tu es invité à mon anniversaire samedi.</body>
    </note>
</notes>
