=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/050_vehicules/vehicules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- auto -->
    <xs:element name="auto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="marque" type="xs:string"/>
                <xs:element name="modele" type="xs:string"/>
                <xs:element name="portes" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- moto -->
    <xs:element name="moto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="marque" type="xs:string"/>
                <xs:element name="modele" type="xs:string"/>
                <xs:element name="cylindree" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Racine -->
    <xs:element name="garage">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="auto" minOccurs="0" maxOccurs="unbounded"/> <!-- notez bien l'utilisation de ref -->
                <xs:element ref="moto" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/050_vehicules/vehicules.xml
<?xml version="1.0" encoding="UTF-8"?>
<garage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="vehicules.xsd">
    <auto>
        <marque>Toyota</marque>
        <modele>Corolla</modele>
        <portes>4</portes>
    </auto>
    <moto>
        <marque>Yamaha</marque>
        <modele>MT-07</modele>
        <cylindree>689</cylindree>
    </moto>
</garage>
