=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/060_commandes_typePerso/commandes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Type réutilisable pour client -->
    <xs:complexType name="ClientType">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Type réutilisable pour produit -->
    <xs:complexType name="ProduitType">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prixUnitaire" type="xs:float"/>
        </xs:sequence>
        <xs:attribute name="quantite" type="xs:float" use="required"/>
    </xs:complexType>

    <xs:element name="commandes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="commande" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="client" type="ClientType"/>
                            <xs:element name="cliente" type="ClientType"/>
                            <xs:element name="produit" type="ProduitType" minOccurs="1" maxOccurs="unbounded" >
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours03_ex1_commande/commandes.xml
<?xml version="1.0" encoding="UTF-8"?>
<commandes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="commandes.xsd">

    <commande numero="CMD001">
        <client>
            <nom>L'Heureux</nom>
            <prenom>Gaston</prenom>
        </client>
        <cliente>
            <nom>L'Heureux</nom>
            <prenom>Louise</prenom>
        </cliente>
        <produit quantite="1">
            <nom>Souris sans fil</nom>
            <prixUnitaire>999.99</prixUnitaire>
        </produit>
    </commande>

    <commande numero="CMD002">
        <client>
            <nom>L'Heureux</nom>
            <prenom>Gaston</prenom>
        </client>
        <cliente>
            <nom>L'Heureux</nom>
            <prenom>Lise</prenom>
        </cliente>
        <produit quantite="2">
            <nom>clavier</nom>
            <prixUnitaire>99.99</prixUnitaire>
        </produit>
        <produit quantite="10">
            <nom>Ã©cran 17 pouces</nom>
            <prixUnitaire>199.99</prixUnitaire>
        </produit>
    </commande>
</commandes>
