=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours03_ex2_locaux/locauxV3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- racine -->
    <xs:element name="locaux">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="local" type="localType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Type rÃ©utilisable pour local -->
    <xs:complexType name="localType">
        <xs:sequence>
            <xs:element name="noLocal">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Q][0-9]{4}"/> <!-- regex -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="nbEtudiant" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== robertAube/134A25-demos-RA/134A25G2/prjDemoProf134/cours03_ex2_locaux/locaux.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Robert AubÃ© -->
<locaux xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="locauxV3.xsd">
    <local> <!-- premier local -->
        <noLocal>F3507</noLocal>
        <nbEtudiant>27</nbEtudiant>
    </local>
    <local>
        <noLocal>Q3517</noLocal>
        <nbEtudiant>28</nbEtudiant>
    </local>
    <local>
        <noLocal>Q3516</noLocal>
        <nbEtudiant>27</nbEtudiant>
    </local>
    <local>
        <noLocal>Q3505</noLocal>
        <nbEtudiant>27</nbEtudiant>
    </local>
</locaux>
