=== robertAube/134A25-demos-RA/134A25G1/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/030_personnes_types/personnes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="age" type="xs:integer"/>
                            <xs:element name="estActif" type="xs:boolean"/> <!-- true ou false -->
                            <xs:element name="taille" type="xs:float"/> <!-- rÃ©el -->
                            <xs:element name="dateNaissance" type="xs:date"/>
                            <xs:element name="heureInscription" type="xs:time"/>
                            <xs:element name="dernierAcces" type="xs:dateTime"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== robertAube/134A25-demos-RA/134A25G1/prjDemoProf134/cours02_XML-XSD/020_XML-XSD/030_personnes_types/personnes.xml
<?xml version="1.0" encoding="UTF-8"?>
<personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="personnes.xsd">
    <personne>
        <nom>Dupont</nom>
        <age>35</age>
        <estActif>false</estActif>
        <taille>1.75</taille>
        <dateNaissance>1990-02-28</dateNaissance>
        <heureInscription>14:30:00</heureInscription>
        <dernierAcces>2025-08-24T14:30:00</dernierAcces>
    </personne>
    <personne>
        <nom>Aub√©</nom>
        <age>75</age>
        <estActif>false</estActif>
        <taille>1.75</taille>
        <dateNaissance>1950-03-04</dateNaissance>
        <heureInscription>14:30:00</heureInscription>
        <dernierAcces>2025-06-24T12:33:10</dernierAcces>
    </personne>
</personnes>
